### ISSUE TITLE
The bit stream is shifted by 8 bits

### ISSUE THREAD

**Issue by Passiday** [electricimp/reference#30]
I am testing your class with a strip of 150 WS2812 LEDs, and discovered that I can not properly control the 0th pixel in the strip. If I'd set it to (0xFF, 0xFF, 0xFF), then the 0th pixel would appear blue, but the 1st - yellow. Obviously, the strip assumes the data are 0x00, 0x00, 0xFF, 0xFF, 0xFF.

I "fixed" the class by introducing a prefix blob containing 8 0xC0 bytes. Now, the physical 1st pixel is the 0th from the program's perspective. And in the device, I will just pretend I have 149 pixels. It's sort of fine in most cases, however not too nice. What could cause such shift, maybe the SPI needs some specific configuration?

[edit]
After more testing, I see that my fix doesn't save from glitches. If the only thing I do in the test() method is to pixelStrip.writeFrame(), the color of the 0th pixel flickers and also the 1st is not white. So, the bit shift changes occasionally. It doesn't matter if the updates are short or long (1s glitches anyway). That makes my Imp+strip project failed, unless I find how to fix this. Perhaps the problem is elsewhere? I know that in the Arduino lib (that controls the strip reliably, so I know the problem is not with the strip) a 50μs long LOW is passed to tell the strip the data packet is over. I don't see this in the Imp class code. Unfortunately I don't own oscilloscope to check the actual output.

**Comment by ersatzavian** [comment]
Hi Passiday,

The WS2812 base code in the repo is a timing compromise between the slightly-different timing standards on the WS2812 and WS2812B. We've seen a lot of cases where they are not reliable when the strip of LEDs is powered at the required 5V but signaled to at the imp's output voltage of 3.3V. The fix is to include a level shifter to shift the signal coming out of the imp from 3.3V to 5V. 

Arduino escapes this issue for two reasons:

1. Tight loops are fine on Arduino, because you're not servicing an IP stack with the same thread of execution you're using to signal to the WS2812s. On the imp, you're using one thread for both jobs, so you can't just bit-bang and get precise timing like you can on Arduino. That's why we use the SPI interface; we hand off a bit stream to the SPI API and the timing is guaranteed. This is also why we don't bit-bang a 50µs "low" at the end of the stream; we can't control that precisely so we just include that at the end of the SPI bit stream instead (by appending 0x00 to the end of the frame buffer we build up in Squirrel)

2. Many Arduinos run at 5V.

Hope this helps!

-T

**Comment by Passiday** [comment]
Thanks for the insights! I'll check how the things change when I apply the level shifting to get the 3.3V signal up to 5V.

Meanwhile, I had opportunity to access a fancy oscilloscope and see how the Imp signal is different from the one coming out from Arduino. The test was sending 1 pixel green, once every 1/100th of a second. The immediate difference was that the oscilloscope had trouble to identify that the signal is exactly identical every time. The one coming out from Arduino was much more identical from instance to instance. Strangely, the widths of "high" sometimes were slightly different in the array of eight "ones", as if the SPI clock was drifting about. Perhaps sometimes such shift adds up and confuses the LED strip?

The next test was setting 10 pixels full green, 100 times a second. The result was that ever so often all 10 pixels flickered full red or full blue, just to get back to full green in the next moment.

**Comment by ersatzavian** [comment]
Sure, I hope I can help!

The SPI Clock should be pretty solid, so if you're seeing timing differences, it's probably something happening outside of the SPI transaction. Something like:

```
pin.write(0);
imp.sleep(0.00005);
pin.write(1);
```

Will vary in length! Which would definitely cause a glitch.

I know that there was an update to the WS2812 base class in the last 4 to 5 weeks; how recently did you pull the code from the repo?

**Comment by Passiday** [comment]
I pulled it about 3 weeks ago. I'll check if there are any differences though.

Could it be that the SPI stream is disturbed by some some background process (ie, maintaining the IP stack) and thus causing tiny delay now and then? Would it help if I double the clock rate and change the "bit" values from byte to word (adjusting the values, of course)?

**Comment by ersatzavian** [comment]
Once the blob is handed off to the SPI, the timing won't be affected by any other processes. Doubling the clock rate and the word values should have no affect on timing, although it will use twice as much memory and take you twice as long to refresh the frame buffer between writes; you'll get a much lower refresh rate on your pixel strip.

**Comment by Passiday** [comment]
Ok, I'll see when I can get access to the oscilloscope and report data instead of anecdote. Who knows, maybe upping the voltage will make the strip happy.
